### ISSUE TITLE
Buffer too small

### ISSUE THREAD

**Issue by Zerogaku** [reidprichard/window_tools#7]
I'm having the same problem as this [issue](https://github.com/reidprichard/window_tools/issues/2), it seems I can only run window tools manuall from the terminal as starting it from my autohotkey script will result in it instantly crashing, but even if I run it manually, for some reason, clicking the windows menu icon with my mouse causes it to instantly crash, like something is triggering it for some reason.
![image](https://github.com/reidprichard/window_tools/assets/144664603/e1d1c7eb-2f09-4305-86d0-d978f3a383de)

**Comment by reidprichard** [comment]
Interesting. I can't fathom why running via AHK would be an issue, and I wasn't able to reproduce that on my end with a simple example:
```
SetWinDelay 0
SendMode("Input")
ProcessSetPriority("H")
SetWorkingDir(A_ScriptDir)

a:: {
	Run "./kanata_helper_daemon.exe -p 1337"
}
```
The above worked without issue. It's been too long since I've been using AHK to recall if the first four lines might have any relevant effect.

However, I fixed the crash when selecting the start menu. It seems that the buffer used to grab process name and window title wasn't long enough in that case, which is odd because it should just be `C:\WINDOWS\explorer.exe`, far less than the 256 chars I allotted for in the buffer. Regardless, doubling that to 512 in ad1b394815d3acc8a859d8b4e385984fcabd1b6c did the trick on my end, and I've uploaded a new [release](https://github.com/reidprichard/window_tools/tree/v0.1.4) with the fix.

**Comment by Zerogaku** [comment]
Hey thanks, after installing the new version opening the windows start menu with the mouse no longer crashes it.
As for it crashing when autostarting with autohotkey, the problem was because of quotation marks around the `--config-file` parameter .
This was the problem line:
```
Run("C:\Users\Null\.config\kanata\kanata_helper_daemon.exe --port=1337 --config-file='C:\Users\Null\.config\kanata\config.kbd' --default-layer=default", , "Hide")
```
this is the working line:
```
Run "C:\Users\Null\.config\kanata\kanata_helper_daemon.exe -p 1337 --config-file=C:\Users\Null\.config\kanata\config.kbd --default-layer=default",, "Hide"
```
Thanks for the help!
